### ISSUE TITLE
Socket closing: Socket connection is getting closed for unknown reasons.

### ISSUE THREAD

**Issue by criticalboot** [washo4evr/Socket.io-v1.x-Library#10]
Hi washo4evr,

I have been using your library with enc28j60, socket.io 1.3.7, and have the following issues/questions. 
1. Communication between the client and server is getting established with the following message
    engine:ws writing "42["welcome",{"message":"Connected !!!!"}]" +0ms

After this any data sent from the client to the server is not received although handshake has happened. After a little while (random number of attempts and unknown time ) it is attempting a reconnection and gets connected properly after which communication happens normally. This behavior is not consistent (random).  

Question: Any idea what is happening here? Am I missing something here?

2. The above behavior at times is followed by a garbage string shown below.

engine:ws writing "42["welcome",{"message":"Connected !!!!"}]" +0ms
  engine:ws received "��65!~Y��17'~^��26%x]��55"xZ�" +952ms

Question: Any thoughts here?

3. I have also been getting transport errors some of them are pasted below. Also error log file with code attached.

engine:polling transport not writable - buffering orderly close +0ms

 [Transport Error file with code.txt](https://github.com/washo4evr/Socket.io-v1.x-Library/files/197666/Transport.Error.file.with.code.txt)

Question: What is the potential cause of these transport errors? 

---
Thank you
Hari

**Comment by washo4evr** [comment]
Hi,
it looks like the 1st message is being sent before upgrading to socket
i believe the issue is in that part of the code :

do{
    if(!client.connect(hostname, port)){
      Serial.println(F("Not connected."));
    }
  } while(!client.connected());
  

I would suggest removing do/while

let me know how it goes.

**Comment by criticalboot** [comment]
Hi washo4evr,
Thank you for your response.
Our problem got resolved otherwise. In the 'setup()' there was a delay(1000)  which was causing the transportation error. By removing this delay problem got resolved.

Appreciate your response and your help to the community via your library and other support. Hope this helps others also.

 Thank you
Hari
