### ISSUE TITLE
Disconnect error

### ISSUE THREAD

**Issue by mitko9000** [washo4evr/Socket.io-v1.x-Library#11]
Hi,

Nice library first I am testing this library sending messages each second for the whole night but at some point I get the module to disconnect from the node.js server.

I want to keep this communication 24/7 alive do you have any idea how can I get a error status or why the chip disconnected ?

**Comment by washo4evr** [comment]
Hi,

did you keep the log?
after how long did it fail?
any error message?

**Comment by mitko9000** [comment]
It happens after ~hour and some minutes its different sometimes appear on every 40 minutes.
I tried without Serial prints but it still hangs event without the logs.

The log is just printing data received from the server every 800ms.

Not sure where to listen to get the error I wrote the following code inside the loop :

 if (!client.connected())
  {
    Serial.println("Error in main loop,some error occur");
  }
when its called I set a beeper to bip so I can hear it and get the end - start timestamp time.

Any ideas how to debug it or  where to listen for errors ?

**Comment by washo4evr** [comment]
I will run something here to make sure
im positive it can run 24/7 as I did in the past.

I will get back to you
as for debugging, serial.println(millis()/1000); would work
you would know exactly when it fails

**Comment by washo4evr** [comment]
btw : what board are you using? esp? w5100 with arduino mega?

**Comment by washo4evr** [comment]
Hi,

I have been running the demo code for over 5h on a ESP8266 without issues.
How is it going on your end?

**Comment by mitko9000** [comment]
Hi I am using sparkfun board esp8266 developer edition.

Also I will attach my node.js code + esp8266 sketch,can you test with it ?
[esp 247 test.zip](https://github.com/washo4evr/Socket.io-v1.x-Library/files/218781/esp.247.test.zip)

**Comment by mitko9000** [comment]
Hi @washo4evr ,

I think I found the problem I was powering on the board from USB 2.0 port per datasheet it written that it can output max of 100mA up to 500mA I decided to change that and hook it up to a DC adapter 5V 1.5A.

And its working for more than 2hours from now.

I will leave it for the night, if I don't have any problems I will close the issue.

**Comment by washo4evr** [comment]
Great
I never had issues like that before with my motherboard but maybe your usb ports get "tired" after a while.
Im glad you got it working

**Comment by mitko9000** [comment]
Yeah it was from the power source
