### ISSUE TITLE
Missing return in SocketIOClient::monitor() ?

### ISSUE THREAD

**Issue by nguidi** [washo4evr/Socket.io-v1.x-Library#12]
Hi there!

I belive there is a missing return in the function `SocketIOClient::monitor()`. I tried your ESP8266 example code and it never leaves this condition `if (client.monitor())` inside the `loop()` function.

If the client isn't connected or available, `SocketIOClient::monitor()` returns 0. I belive this function should return 1 if everything is OK and the message was parsed.

**Comment by washo4evr** [comment]
it should leave the monitor function when there's nothing in the Serial
then, inside monitor, it runs function parser when Index is found
Therefore, I dont think something is missing but I'm willing to look into it.
could you provide me with some more info?

**Comment by BhanuTejaJ** [comment]
There is no "1 or true" return in "SocketIOClient::monitor" function , So it always returns zero... and there is no chance of getting to  if (client.monitor()) in loop. 

I too had the same problem.. and fixed it by adding a return. Thanks a lot for the library :)

**Comment by washo4evr** [comment]
Indeed
it only returns 0
if (!client.available())
	{
		return 0;
	}

Feel free to suggest your code and I will merge it
thanks guys

**Comment by guilhermelirio** [comment]
> 
> 
> Indeed
> it only returns 0
> if (!client.available())
> {
> return 0;
> }
> 
> Feel free to suggest your code and I will merge it
> thanks guys

You have solution? Don't work with me =/

**Comment by jbteja** [comment]
After all these years, I wonder why no one raised a PR for adding a return.

**Comment by jbteja** [comment]
> Indeed
> it only returns 0
> if (!client.available())
> {
> return 0;
> }
> 
> Feel free to suggest your code and I will merge it
> thanks guys

Would like to raise a PR for adding return. Please look into the change and merge it. Thanks.
