### ISSUE TITLE
dataArrivedDelegate

### ISSUE THREAD

**Issue by jpeskar** [washo4evr/Socket.io-v1.x-Library#15]
Is this  legacy of the Billory fork? I'm trying to wrap my head around what it is doing. In the Billory file it fork it gets called in the monitor function. If it is not used I would propose removing it.

**Comment by washo4evr** [comment]
Hi,
yes, my first draft was based on Billroy's work
He is credited in the opening
Since that time, the library has changed quite a bit
datadelegate is not even needed anymore

work is crazy here too
Library needs some love
Hopefully I have some time next weekend

**Comment by jpeskar** [comment]
I saw the credit and it looked like the datadelegate was deprecated. I just wanted to understand. I'm looking at taking a crack at the parsing the return JSON. I just wanted to ensure that I understood the flow before I started making changes.
