### ISSUE TITLE
no spi.h error

### ISSUE THREAD

**Issue by luxnovalabs** [washo4evr/Socket.io-v1.x-Library#2]
I get this error. i have both the github version and the board manager version, and have tried all variations listed of the board:

libraries/Socket.io/SocketIOClient.h:36:17: fatal error: SPI.h: No such file or directory
 #include "SPI.h"

**Comment by washo4evr** [comment]
spi.h should be included in the arduino IDE.
I suggest you reinstall that latest version to be sure
which board are you trying to use with socket.io?
ESP8266? regular arduino boards (mega, uno, nano)?

**Comment by washo4evr** [comment]
Is it OK? Does it work now?

**Comment by luxnovalabs** [comment]
holy crap. that's me in the previous comments. it was 2am when i was trying this last. i don't even remember posting that. but i'm trying again, and got to the same place, only to see i've been here before.

ok. here's where i'm at. you were right, i was on arduino 1.6.5. i've updated to 1.6.7 and the spi.h error is gone. i get  warning for category ' ' not being valid in the json library, but it compiles fine, and I'm working out getting it to connect. thanks for the library and responsiveness.

**Comment by washo4evr** [comment]
Im glad you got it working.
the json part is still experimental
I will update the library as soon as I reach stable version
