### ISSUE TITLE
Cannot send/receive event from socket.io 1.4.5

### ISSUE THREAD

**Issue by akirapix** [washo4evr/Socket.io-v1.x-Library#3]
Hi,
i have been able to compile and run your project. I am using a arduino uno compatible with HanRun ENC28J60 chip. 
I am able to enstablish a connection but not to send receive events.

```
socket.io:client writing packet {"type":2,"data":["welcome",{"message":"Connected !!!!"}],"nsp":"/"} +0ms
  socket.io-parser encoding packet {"type":2,"data":["welcome",{"message":"Connected !!!!"}],"nsp":"/"} +0ms
  socket.io-parser encoded {"type":2,"data":["welcome",{"message":"Connected !!!!"}],"nsp":"/"} as 2["welcome",{"message":"Connected !!!!"}] +0ms
  engine:socket sending packet "message" (2["welcome",{"message":"Connected !!!!"}]) +0ms
  socket.io:socket joined room /#idg72gEglm8e9xeJAAAB +1ms
  engine:polling closing +1m
  engine:polling transport not writable - buffering orderly close +0ms
  socket.io:client client close with reason ping timeout +0ms
  socket.io:socket closing socket - reason ping timeout +0ms 
```

this is my socket.io log. I really do not have any ideas to solve this.

**Comment by washo4evr** [comment]
maybe something to do with the new 1.4.5 version.
I will run some tests and get back to you.

**Comment by akirapix** [comment]
Making some experiments i found:

```
engine:socket might upgrade socket transport from "polling" to "websocket" +0ms
engine:socket client did not complete upgrade - closing transport +10s
engine:ws closing +1ms
engine:polling closing +31s
engine:polling transport not writable - buffering orderly close +0ms
```

i think that the key is the 'socket did not complete upgrade'...

Can you please tell me wich version of socket.io should be working? Thanks

**Comment by washo4evr** [comment]
I made successful connections with Node.JS version 4.1.1 & Socket.IO version 1.3.7
the socket should upgrade.
I will need to wireshark it to see

**Comment by akirapix** [comment]
I have tried with Socket.io 1.3.7 and node.js 4.1.1with no luck
I see the problem is always 'socket client did not complete upgrade - closing transport'.
Maybe that Arduino UNO clone is to 'weak' to correctly manage ENC28J60 chip?
Everything works fine with W5100. 
Now i think i will try to put some delay in readHandshake method...

**Comment by akirapix** [comment]
I finally solved it using an arduino mega.
It looks like arduino uno has not enough power/memory to manage a socket.io connection

**Comment by washo4evr** [comment]
thank you for letting me know
I will add that to the main page so others don't have the same issue
