### ISSUE TITLE
ESP8266 Connection failed ?

### ISSUE THREAD

**Issue by ftx** [washo4evr/Socket.io-v1.x-Library#45]
Hello,

I have just take your example and launch nodejs app.
All is ok but after the connection, i have a problem.

![capture du 2017-08-25 17-04-20](https://user-images.githubusercontent.com/1889424/29719728-9f5da0c4-89b7-11e7-985b-cf4adbce5ce0.png)

And no answer from server.

**Comment by washo4evr** [comment]
Hi,

can you check if you have a firewall issue?
This happens frequently

Let me know
