### ISSUE TITLE
Help with library usage.

### ISSUE THREAD

**Issue by Ruttmann** [washo4evr/Socket.io-v1.x-Library#54]
Hello @washo4evr !

First of all, sorry if I'm using the wrong place to ask this question, but I didn't found any other way of contact...

I want to know exactly what is the meaning of parameters RID, Rname and Rcontent.

Rcontent I know that is the content of the message itself, it is the "payload", right?

But what should I do with RID and Rname? I'm running the example, but didn't realized what's the real use for these parameters on Server and Client side. I see on server side that are mentions to the Strings 'connection' and 'atime' that, obviously, are triggered on connection event and on Arduino regular asking for time. When asking for a time, Arduino always send "message" as Rname, but I didn't found any use of this parameter on server side.

In my mind, RID is something like a "session identifier"? I couldn't realize a good usage for Rname...

Could you please clarify?

Thanks!

**Comment by washo4evr** [comment]
Hello,
in that example from the app.js
io.sockets.emit('atime', { time: new Date().toJSON() });

RID = atime
Rname = time
Rcontent = new Date().toJSON()

in the ino file, you have
client.send("atime", "message", "Time please?");
RID = "atime"
Rname = "message"
Rcontent = "Time please?"

I hope this explains it better

**Comment by Ruttmann** [comment]
This explains everything. Thank you very much!
