### ISSUE TITLE
need help with debugging details

### ISSUE THREAD

**Issue by itsjesseyo** [washo4evr/Socket.io-v1.x-Library#7]
in the c++ file i've uncommented every line that Serial prints and says it can be used for debugging. The problem is that nothing seems to print to the console. i only get

wdt reset
 ets Jan  8 2013,rst cause:4, boot mode:(1,6)
and sometimes hex blocks.

I'm used to debugging regular arduinos, and I'm to the point i think maybe i should switch esp8266 modules. I'm currently using the nodemcu 1.0, but i own the adafruit version, for example.

So, I guess what I'm asking for is some control experiment advice.

What modules are you using?
Is there some special way to get these particular serial statement out besides the arduino serial window?
wdt reset, and rst cause 4 are from the esp8266 firmware related to watchdog timer. Are you calling for a soft reset somehow?

**Comment by washo4evr** [comment]
hey,
this is not normal
you should see some debugging.
one of the commented line will actually Serial.print everything that is received.
I use [http://www.banggood.com/Geekcreit-Doit-NodeMcu-Lua-ESP8266-ESP-12E-WIFI-Development-Board-p-985891.html](http://www.banggood.com/Geekcreit-Doit-NodeMcu-Lua-ESP8266-ESP-12E-WIFI-Development-Board-p-985891.html)
Im not sure how to check the firmware version
Im not calling directly for any reset.
it might be inside the esp*wifi.h
if you are not getting any serial.print, i would suggest trying a new module as yours might be defective

**Comment by itsjesseyo** [comment]
thanks for continuing to be helpful.

there's a setting for binary in the server i'm exploring that you could help identify a possible conflict with...

True to support binary payloads, False to treat all payloads as text. On Python 2, if this is set to True, unicode values are treated as text, and str and bytes values are treated as binary. This option has no effect on Python 3, where text and binary payloads are always automatically discovered.

the default is false, so everything is treated as text. think that there might be a clue there? I've tried with and without already, but i'm also going to upgrade to python 3 and see if it solves itself, as the text suggests.

**Comment by itsjesseyo** [comment]
ok. putting some more details up....

i used an adafruit huzzah esp8266, a custom board with a 12-q, and the nodemcu knockoff, and all errors are all the same on all boards. I ordered your exact board via that link you shared. i'd add it to my list. Mind if i help with the wiki when we get this figured out?

However, my nodemcu does apparently require a complete unplug and replug to to actually work correctly - so lets ignore those reset errors and call it user error. 

FOR ANYONE READING IN THE FUTURE : try programing the board, then unplug it and plug it in again and the wdt rst, and reset error code 4, might just go away. 

I also my have gotten similar eror codes at work simply because the router is set to require the latest spec "AC" and the esp only goes to n, but it's unverified.

**Comment by washo4evr** [comment]
I hope you get your new ESP soon so we can do some more testing
did you update to Python 3 already?
My board doesnt require to be unplugged after programming

I would love some help on a wiki
I really want to finish (bugfixes, REST, ...) and maintain that library.

**Comment by itsjesseyo** [comment]
i did update to python3. same exact errors. at least it's consistent now. errors don't bug me. inconsistent ones drive me nuts.[looks at wiki]

**Comment by itsjesseyo** [comment]
wiki started

**Comment by washo4evr** [comment]
awesome
